### ISSUE TITLE
[FEATURE REQUEST]  GET ALL UNFLAGGED  COMMENTS ON A REPORT

### ISSUE THREAD

**Issue by AironDev** [microapidev/comment-microapi#10]
###GET ALL COMMENTS (UNFLAGGED)
Controller method that returns ony unflagged comments on a particular expense report for web display

###Solution
Write a controller method and endpoint URL that returns only unflagged comments on a particular expense report

**Comment by Lihemen** [comment]
Can I take this?

**Comment by simply-alliv** [comment]
This endpoint does not exist anymore as the `GET /comments` endpoint will be handling this through a query parameter (isFlagged). See the updated swagger documentation for more information.

So I will close this issue and it's PR. Sorry for the inconvenience. Things will be much more structured moving forward.
