### ISSUE TITLE
[FEATURE REQUEST] UPDATE COMMENTS

### ISSUE THREAD

**Issue by AironDev** [microapidev/comment-microapi#11]
### UPDATE COMMENTS
Controller and API endpoint for updating comments

### Describe the solution you'd like
Authenticated user should be able to edit his/her comments and if possible edited comments should carry the label "edited"

### Additional context
Edited comments should recognizable, by including an "edited" label

**Comment by Lihemen** [comment]
Can I take this?

And also can the comment model be updated to include the ‘edited’ property. It can be set to false by default
