### ISSUE TITLE
[FEATURE REQUEST] RepliesController - PATCH /comments/{commentId}/replies/{replyId}: Create controller method to update a reply

### ISSUE THREAD

**Issue by Myspheet** [microapidev/comment-microapi#117]

**Comment by davidalenoghena** [comment]
How does this assignment work? I created the issue or update reply before you but it wasn't assigned to me.

**Comment by Myspheet** [comment]
> How does this assignment work? I created the issue or update reply before you but it wasn't assigned to me.

Who ever gets assigned the task, gets to work on it. That's how it works.

**Comment by simply-alliv** [comment]
This issue is now closed due to inactivity. It will now be reassigned. 

Please kindly look for another available task on the sheet when you are ready.
