### ISSUE TITLE
[FEATURE REQUEST] RepliesController - DELETE /comments/{commentId}/replies/{replyId}

### ISSUE THREAD

**Issue by Simeon979** [microapidev/comment-microapi#126]
### Is your feature request related to a problem? Please describe.
Implement the `DELETE /comments/{commentId}/replies/{replyId}` route

### Describe the solution you'd like
* Add the route for deleting replies
* Add the controller
* Add tests

**Comment by oscar-ekeyekwu** [comment]
please try and update your issue name to be same with what is in the sheet. also drop your request in the thread provided on the channel

**Comment by Simeon979** [comment]
@oscar-ekeyekwu  I'm not sure which thread you're talking about. Also, concerning the sheet, if you're talking about this one https://docs.google.com/spreadsheets/d/1KAMyYZVw3vS0KpeBC7FC4g_zpzbtPGMOxbVhC5mPHyg/edit#gid=1073018958  the issue is not there

**Comment by oscar-ekeyekwu** [comment]
@Simeon979 Please Which sub team are you in ?

**Comment by Simeon979** [comment]
@oscar-ekeyekwu I'm only in the #new-jl-backendapi channel. Is there a separate one for comment microapi?
