### ISSUE TITLE
[FEATURE REQUEST]use @hapi/joi for schema description and data validation

### ISSUE THREAD

**Issue by Clish254** [microapidev/comment-microapi#13]
### Is your feature request related to a problem? Please describe.
It is important to do validation of data from a user before persisting it in the db.Data validation can get very complex especially when dealing with multiple schemas like we are. 
### Describe the solution you'd like
@hapi/joi is a module that is used to define a schema or blueprint of Javascript objects. Once the schema is defined, you then can use Joi's handy methods that come bundled with it, to validate any other objects against the schema. In our case the req.body will be compared with a schema we describe using @hapi/joi. @hapi/joi will also create detailed error messages for us so we don't have to write error messages again and again for every case.
### Describe alternatives you've considered
I've considered writing all the validation from scatch for all the schemas but this can get long and clutter our code.

### Additional context
With @hapi/joi we can just describe a schema and compare it with data sent by a user every time a POST request is made.Joi will validate the data and create a detailed error message if any errors are found.

I'd like to work on this so please assign this to me if this issue is accepted.

**Comment by simply-alliv** [comment]
Can I work on this?
