### ISSUE TITLE
[chore]: Document Endpoint & Response Format 

### ISSUE THREAD

**Issue by oscar-ekeyekwu** [microapidev/comment-microapi#14]
### Is your feature request related to a problem? Please describe.

This Document will be a guide to the contributors for them to know how to return their responses and routes. 
And also aid easy documentation of the API Endpoints

### Describe the solution you'd like
Swagger Documentation Tool for the API Documentation

### Describe alternatives you've considered
Aternative Considered is Apiary

### Additional context
None

**Comment by simply-alliv** [comment]
@oscar-ekeyekwu Should this issue be closed?
