### ISSUE TITLE
[TEST]: CommentsEndpointTests - GET /comments/{commentId}/votes:

### ISSUE THREAD

**Issue by oscar-ekeyekwu** [microapidev/comment-microapi#145]
### Is your feature request related to a problem? Please describe.
Write test for `GET /comments/:commentId/votes` endpoint

### Describe the solution you'd like
- [x] TEST SUITE: `GET /comments/:commentId/votes`

**Comment by adebayoileri** [comment]
Can I work on this

**Comment by simply-alliv** [comment]
> Can I work on this

@adebayoileri Please check out the sheet linked to on the pinned messages in the FGExpense backend channel.
