### ISSUE TITLE
[FEATURE REQUEST] : Create controller method to upvote a reply

### ISSUE THREAD

**Issue by Ochuwa-sophie** [microapidev/comment-microapi#159]
The purpose of this feature is to give users the ability to upvote replies.

"RepliesController - PATCH /comments/{commentId}/replies/{replyId}/votes/upvote:
Create controller method to upvote a reply"

**Comment by davidalenoghena** [comment]
Isn't this a duplicate of case #117 that is already assigned to someone?

**Comment by Ochuwa-sophie** [comment]
No, this is to **upvote** a reply while #117 is to **update** a reply

**Comment by Joeedwin073** [comment]
I'll like to take this task.
Thanks
