### ISSUE TITLE
[FEATURE REQUEST] - Add invalid route handler

### ISSUE THREAD

**Issue by dave-ok** [microapidev/comment-microapi#16]
### Is your feature request related to a problem? Please describe.
There is no invalid route handler

### Describe the solution you'd like
Create a catch-all route for non-existent endpoints. In other words a `404` route handler

### Additional context
Currently, invalid routes crash the server because there is no default route handler

**Comment by Aptcoder** [comment]
can I work on this

**Comment by dave-ok** [comment]
You have 2 hours to deliver
