### ISSUE TITLE
[BUG] Comment Upvote and Downvote controllers message fix

### ISSUE THREAD

**Issue by papa28x4** [microapidev/comment-microapi#211]
### Describe the bug
50% of the time the message returned by either the upvote or downvote controller is wrong.

### To Reproduce

1) Choose a sample ownerId 
```
{
  "ownerId": "myMail@example.com"
}

```
2) Using POSTMAN make a PATCH request to http://localhost:4000/comments/{commentId}/replies/{replyId}/votes/upvote

3) First time you do, myMail@example.com is added to upvote array. "Comment Upvoted Successfully" is correctly returned. 
4) If you repeat the PATCH request with the same ownerId, myMail@example.com is removed from the upvote array but the message sent from the controller still reads "Comment Upvoted Successfully"

### Expected behavior
When a user clicks to upvote a comment for the first time, the message sent should read **"Comment Upvoted Successfully"**  but if a comment has already been upvoted by a user and that same user clicks again, the message should read **"Upvote removed"** but the current implementation returns **"Comment Upvoted Successfully"** for both scenarios. The same is true for the downvote controller

**Comment by simply-alliv** [comment]
Thank you for seeing this and being proactive about it. Really appreciate it.

**Comment by simply-alliv** [comment]
Anyway, I'd suggest that you use these two messages, "Comment upvote added successfully" and "Comment upvote removed successfully".

**Comment by papa28x4** [comment]
Noted. I have done as advised
