### ISSUE TITLE
[FEATURE REQUEST] Add a test database for test env 

### ISSUE THREAD

**Issue by Aptcoder** [microapidev/comment-microapi#24]
### Is your feature request related to a problem? Please describe.

- When a test case is created that has to do with database manipulations ,the current database will be affected

### Describe the solution you'd like
- A new database for tests which will be used in test environments 
  * create a new database for tests
  * add a new config file for handling the different parameters by environment
  * change the url in mongoose config to point at new test DB

**Comment by Aptcoder** [comment]
can I be assigned to this

**Comment by oscar-ekeyekwu** [comment]
How do you want to implement this test DB, from your local or cloud

**Comment by Aptcoder** [comment]
cloud so everyone does not always have to configure.

Has this been handled

**Comment by oscar-ekeyekwu** [comment]
we currently have a db on cloud, which will not be used upon live deployment.. so its more or less a test db, requests and responses are gotten from there actually
