### ISSUE TITLE
[FEATURE REQUEST] ApplicationsController - DELETE /applications/{applicatonId}

### ISSUE THREAD

**Issue by Clish254** [microapidev/comment-microapi#252]
### Is your feature request related to a problem? Please describe.

To Create a controller method to delete an application of an organization by Id
### Describe the solution you'd like

When a DELETE request is made to this endpoint the id in the request parameters should be used to delete the application.
### Describe alternatives you've considered
N/A in this case

**Comment by dave-ok** [comment]
@Clish254 Are you still working on this task? Please indicate. If not the task needs to be reassigned. Thanks

**Comment by Clish254** [comment]
> @Clish254 Are you still working on this task? Please indicate. If not the task needs to be reassigned. Thanks

Yes, i was waiting for directions in the channel. I've already worked on this.

**Comment by dave-ok** [comment]
@Clish254 You seem to have closed all the PRs you were working on. Kindly sync your local repo as a few updates have been made. We eagerly await your PR as this is a critical feature it needs to be resolved ASAP. Thanks

**Comment by Clish254** [comment]
Okay, I closed them because of the issues we had on Saturday.
