### ISSUE TITLE
[FEATURE REQUEST] ApplicationsController - GET /applications/{applicationId}

### ISSUE THREAD

**Issue by davidalenoghena** [microapidev/comment-microapi#255]
### Describe the solution you'd like
Create controller method to get an application

**Comment by dave-ok** [comment]
@davidalenoghena If you are still working on this task or not please indicate. If you are not the task needs to be reassigned.

**Comment by davidalenoghena** [comment]
Yes, I am working on it. Will deliver it today. Sorry for the delay
