### ISSUE TITLE
bug: Refractor of the API documentation

### ISSUE THREAD

**Issue by Alao-Abiodun** [microapidev/comment-microapi#26]
### Describe the bug
Refractor of the swagger documentation of API

### To Reproduce
1. Change the file into multiple files
2. Then we create the main file for the YAML definition
3. Each of the files will reference the main file.

### Expected behavior
To ease the teammates that will work on the API docs issue and to prevent breaking changes in code.

### Screenshots
No

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version 83.0.4103.116

### Additional context
No

**Comment by dave-ok** [comment]
@Alao-Abiodun Please work with @simply-alliv to ensure you get this right. Thanks

**Comment by dave-ok** [comment]
@Alao-Abiodun You have 1 hr to complete this

**Comment by Alao-Abiodun** [comment]
My PC went off, So I just went to buy fuel to switch on my generator.

**Comment by dave-ok** [comment]
This issue had been resolved in #45
