### ISSUE TITLE
[FEATURE REQUEST] Validation for name and email in model user.js

### ISSUE THREAD

**Issue by davidalenoghena** [microapidev/comment-microapi#37]
### Is your feature request related to a problem? Please describe.
There is no validation of the email to be entered

### Describe the solution you'd like
Validation of emails entered and to return an error when an incorrect email is sent

**Comment by The-indigo** [comment]
i want to work on this

**Comment by davidalenoghena** [comment]
I also want to work on it

**Comment by davidalenoghena** [comment]
Can it be assigned to me?

**Comment by oscar-ekeyekwu** [comment]
This issue is a duplicate of #13
