### ISSUE TITLE
[FEATURE REQUEST] Create Swagger documentation for Comments API 

### ISSUE THREAD

**Issue by simply-alliv** [microapidev/comment-microapi#39]
### Is your feature request related to a problem? Please describe.
Documentation is required so that consumers of the API have a clear idea of how the API works and what is expected of them when using the API and its endpoints.

### Describe the solution you'd like
Create documentation for each comments endpoint, its method, the required body, the response body, and the other possible responses.

### Describe alternatives you've considered
None.

### Additional context
For more information, see the [Contribution documentation](https://github.com/microapidev/comment-microapi/blob/develop/Contributions.md).

**Comment by dave-ok** [comment]
@simply-alliv We will appreciate if u can help us get this up. Thanks
