### ISSUE TITLE
[FEATURE REQUEST]: Create validation middleware for validation rules

### ISSUE THREAD

**Issue by dave-ok** [microapidev/comment-microapi#40]
### Is your feature request related to a problem? Please describe.
Various endpoints will need request data or parameters to be validated. This middleware when placed in a particular route and supplied validation rules should accept or reject with an appropriate response

### Describe the solution you'd like
Implementation of validation middleware using Joi validation package

**Comment by simply-alliv** [comment]
Can I get assigned to this task?

**Comment by simply-alliv** [comment]
Can I get assigned to this?
