### ISSUE TITLE
[TEST] getApplicationToken.test.js

### ISSUE THREAD

**Issue by davidalenoghena** [microapidev/comment-microapi#408]
### Is your feature request related to a problem? Please describe.
Implement a test suite that will cover all required functionality expected from the `getApplicationToken.test.js` endpoint `/v1/applications​/{applicationId}​/token`

### Describe the solution you'd like
_Test if controller returns status:_
- 201 - if an application token is successfully generated

**Comment by simply-alliv** [comment]
Due to PR #406 and it's linked issue, I will close this issue.
