### ISSUE TITLE
[BUG] POST /applications not return application name on save

### ISSUE THREAD

**Issue by EricoMartin** [microapidev/comment-microapi#409]
### Describe the bug
POST /applications  endpoint does not return application name on save

### To Reproduce
1. Go to 'POST /applications endpoint'
2. See error

### Expected behavior
The endpoint should return application name on save.

**Comment by simply-alliv** [comment]
Are you sure that this is a bug? The swagger documentation for this endpoint shows that the application's name is not part of the response.

**Comment by EricoMartin** [comment]
yea i saw that too. ill close this
