### ISSUE TITLE
[Test]: Write Test Cases for GET Requests

### ISSUE THREAD

**Issue by oscar-ekeyekwu** [microapidev/comment-microapi#47]
### Is your feature request related to a problem? Please describe.
Code can break, and response not handled properly. To avoid code breaking on live, test cases need be passed and routes coverage be maximum

### Describe the solution you'd like
Write test cases using jest for listed endpoints on the Documentation

### Additional context
No

**Comment by piouson** [comment]
hey @oscar-ekeyekwu do you want to comment what you plan to write so no duplicate work..?

- [ ] GET /comments - PR #58 
- [ ] GET /comments/refs/{refId}
- [ ] GET /comments/{commentId}/replies
- [ ] POST /comments
- [ ] POST /comments/{commentId}/replies
- [ ] DELETE /comments/{commentId}
- [ ] DELETE /comments/{commentId}/replies/{replyId}
- [ ] PATCH /comments/{commentId}
- [ ] PATCH /comments/{commentId}/votes
- [ ] PATCH /comments/{commentId}/votes
- [ ] PATCH /comments/{commentId}/flag
- [ ] PATCH /comments/{commentId}/replies/{replyId}
- [ ] PATCH /comments/{commentId}/replies/{replyId}/votes
- [ ] PATCH /comments/{commentId}/replies/{replyId}/flag

**Comment by oscar-ekeyekwu** [comment]
@piouson I have edited it so others can pick the posts and work on them
