### ISSUE TITLE
[BUG] comment model is not well reference to other model

### ISSUE THREAD

**Issue by Alao-Abiodun** [microapidev/comment-microapi#51]
### Describe the bug
The comment model is not referencing other models appropriately.

### To Reproduce
1. Go to controller
2. Click on the comment.js file inside the controller
3. Scroll down to see the schema of the model.
4. see an error: Schema.Types.ObjectId.

### Expected behavior
It should be:  mongoose.Schema.Types.ObjectId

### Screenshots
![comment](https://user-images.githubusercontent.com/46402042/85888010-ad85b600-b7e0-11ea-9581-e618eb4dd117.PNG)

### Desktop (please complete the following information):
 - OS: [windows]
 - Browser [chrome]
 - Version 83.0.4103.116

### Additional context
No

**Comment by oscar-ekeyekwu** [comment]
Sorry, this is not an issue
