### ISSUE TITLE
[FEATURE REQUEST] Get all the comment for specific reference id

### ISSUE THREAD

**Issue by Alao-Abiodun** [microapidev/comment-microapi#53]
U### Is your feature request related to a problem? Please describe.
Users should be able to get all comments for a particular referenceId (i.e user).

### Describe the solution you'd like
A controller to get all comment for a specific reference Id
Endpoints: /comment/refs/:{refId}

### Describe alternatives you've considered
No alternative

### Additional context
No

### Time Duration to finish
50mins

**Comment by dave-ok** [comment]
Please ensure you use the updated docs at https://comments-microservice.herokuapp.com/
