### ISSUE TITLE
[FEATURE REQUEST] controller function upvote or downote a user comment

### ISSUE THREAD

**Issue by EricoMartin** [microapidev/comment-microapi#55]
### Feature
The user comment can be upvoted or downvoted based on the app requirements
### Describe the solution you'd like
A user comment can be upvoted or downvoted and the number of votes recorded and dispalyed
### Route
'/comments/{commentId}/votes'

**Comment by oscar-ekeyekwu** [comment]
@EricoMartin did you see the revert of the and comment

**Comment by EricoMartin** [comment]
I'm just seeing this now. i just created an issue for a bug fix. Anyway please what error did you notice please?
