### ISSUE TITLE
[FEATURE REQUEST] User can reply to a comment

### ISSUE THREAD

**Issue by neymarjimoh** [microapidev/comment-microapi#62]
###  Overview

- Users can make replies to a comment

**Comment by neymarjimoh** [comment]
I am working on this

**Comment by neymarjimoh** [comment]
@piouson @dave-ok  can I work on this?

**Comment by piouson** [comment]
> @piouson @dave-ok  can I work on this?

@neymarjimoh I believe a PR was merged for this or still open.. I'm on mobile right now, will check and let you know..

**Comment by neymarjimoh** [comment]
Ok no problem
