### ISSUE TITLE
[FEATURE REQUEST]Controller function to react to replies of comments by upvotes or downvotes

### ISSUE THREAD

**Issue by neymarjimoh** [microapidev/comment-microapi#63]
### Overview

- After replies are made to a specific comment, users can react to these replies by **upvoting** if the reply is ok to them or **downvoting** the reply if not

**Comment by neymarjimoh** [comment]
This is already taken by me

**Comment by neymarjimoh** [comment]
@dave-ok  can I work on this?

**Comment by neymarjimoh** [comment]
@piouson @dave-ok  @Aptcoder  i have checked there's no PR or issue on this. Can i work on it?

**Comment by piouson** [comment]
Yes please, go for it. Check the swagger docs and discuss any questions here..

**Comment by neymarjimoh** [comment]
Ok.. thanks
I'd check it out

**Comment by neymarjimoh** [comment]
The docs contain a single endpoint for upvoting and downvoting. It requires a body containg the votetype.
I don't think this is a good way of implementing this

**Comment by neymarjimoh** [comment]
I've done similar thing on a project, I think we should have 2 different endpoints for that` **/votes/upvote**` and **`/votes/downvote`**
Such that hitting on a button that signifies upvotes will route the request to the upvote endpoint and do the business logic there then increment it likewise for downvote
This is what I feel boss @piouson

**Comment by neymarjimoh** [comment]
Which method should I use @piouson

**Comment by piouson** [comment]
Hey @neymarjimoh please mention/dm me in slack so we talk more on this..
We will go with your idea on this, thank you!

The API is currently in the design phase and have already gone through about 3 iterations, we can use your insight with completing the design..

**Comment by neymarjimoh** [comment]
Ok.thanks
