### ISSUE TITLE
[FEATURE REQUEST]Users can flag off comments

### ISSUE THREAD

**Issue by neymarjimoh** [microapidev/comment-microapi#64]
### Overview
- **Users can flag off comments**
This will update the comment as being flagged and the number of times a comment is being flagged off is shown which increases or decreases as the case may be

**Comment by neymarjimoh** [comment]
I can work on this ASAP
slack username is @jimoh19

**Comment by neymarjimoh** [comment]
Working on this

**Comment by oscar-ekeyekwu** [comment]
Done
