### ISSUE TITLE
[FEAT]: Create Controller method to return all replies of a Comment

### ISSUE THREAD

**Issue by oscar-ekeyekwu** [microapidev/comment-microapi#72]
### Is your feature request related to a problem? Please describe.
This feature will return all replies under a comment and return as json

### Describe the solution you'd like
A controller method to implement the endpoint /comments/{commentId}/replies

**Comment by The-indigo** [comment]
can i work on this

**Comment by oscar-ekeyekwu** [comment]
i am working on it already
@The-indigo

**Comment by oscar-ekeyekwu** [comment]
Create another issue, there are works to be done
