### ISSUE TITLE
[TEST FEATURE ] write unit tests for downvote and upvote of comments

### ISSUE THREAD

**Issue by EricoMartin** [microapidev/comment-microapi#75]
###Test Feature .
Test cases for downvote and upvote of comments

### Description

A Jest test suite function that  tests downvote and upvote of comments controller functionality.

**Comment by Simeon979** [comment]
I can work on this

**Comment by piouson** [comment]
hey @Simeon979 did you begin work yet..?

**Comment by Simeon979** [comment]
I wanted to be sure first @piouson But I will begin now
